export const SET_USER = 'SET_USER'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const UPDATE_NAME = 'UPDATE_NAME'
export const HOME_MODE = 'HOME_MODE'

export const GAME_CONNECT = 'GAME_CONNECT'
export const GAME_CONNECT_PENDING = 'GAME_CONNECT_PENDING'
export const GAME_DISCONNECT = 'GAME_DISCONNECT'
export const GAME_SET_STATE = 'GAME_SET_STATE'
export const GAME_SET_ME = 'GAME_SET_ME'
export const GAME_CARD_SELECT = 'GAME_CARD_SELECT'
export const GAME_MSG_TOGGLE = 'GAME_MSG_TOGGLE'
export const GAME_OVER = 'GAME_OVER'
export const GAME_RESET = 'GAME_RESET'
export const GAME_LOST_OPP = 'GAME_LOST_OPP'


export const DIALOG_EXIT = 'DIALOG_EXIT'
export const DIALOG_DISCONNECT = 'DIALOG_DISCONNECT'
export const DIALOG_MSG = 'DIALOG_MSG'

