export const SET_USER = 'SET_USER'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const UPDATE_NAME = 'UPDATE_NAME'

export const FORM_UPDATE_NAME = 'FORM_UPDATE_NAME'
export const FORM_UPDATE_EMAIL = 'FORM_UPDATE_EMAIL'
export const FORM_UPDATE_PASSWORD = 'FORM_UPDATE_PASSWORD'
export const FORM_UPDATE_PASSWORD2 = 'FORM_UPDATE_PASSWORD2'
export const FORM_UPDATE_OLD_PASSWORD = 'FORM_UPDATE_OLD_PASSWORD'
export const FORM_ERROR = 'FORM_ERROR'
export const FORM_CLEAR = 'FORM_CLEAR'

export const SET_GAME = 'SET_GAME'
